services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-posgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-main_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_main:/var/lib/postgresql/data
volumes:
  postgres_main: